/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCCommunityIdRouteImport } from './routes/_authenticated/c.$communityId'
import { Route as AuthenticatedDmPeerIdRouteImport } from './routes/_authenticated/dm.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCCommunityIdRoute =
  AuthenticatedCCommunityIdRouteImport.update({
    id: '/c/$communityId',
    path: '/c/$communityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDmPeerIdRoute = AuthenticatedDmPeerIdRouteImport.update({
  id: '/dm/$peerId',
  path: '/dm/$peerId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/c/$communityId': typeof AuthenticatedCCommunityIdRoute
  '/dm/$peerId': typeof AuthenticatedDmPeerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/c/$communityId': typeof AuthenticatedCCommunityIdRoute
  '/dm/$peerId': typeof AuthenticatedDmPeerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/c/$communityId': typeof AuthenticatedCCommunityIdRoute
  '/_authenticated/dm/$peerId': typeof AuthenticatedDmPeerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/c/$communityId'
    | '/dm/$peerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/c/$communityId'
    | '/dm/$peerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/discover'
    | '/_authenticated/friends'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/c/$communityId'
    | '/_authenticated/dm/$peerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$communityId': {
      id: '/_authenticated/c/$communityId'
      path: '/c/$communityId'
      fullPath: '/c/$communityId'
      preLoaderRoute: typeof AuthenticatedCCommunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm/$peerId': {
      id: '/_authenticated/dm/$peerId'
      path: '/dm/$peerId'
      fullPath: '/dm/$peerId'
      preLoaderRoute: typeof AuthenticatedDmPeerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCCommunityIdRoute: typeof AuthenticatedCCommunityIdRoute
  AuthenticatedDmPeerIdRoute: typeof AuthenticatedDmPeerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCCommunityIdRoute: AuthenticatedCCommunityIdRoute,
  AuthenticatedDmPeerIdRoute: AuthenticatedDmPeerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
